# Generated by Django 5.0.2 on 2024-02-21 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('kra_pin', models.CharField(max_length=50)),
                ('business_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('registration_certificate', models.FileField(upload_to='documents/')),
                ('trading_license', models.FileField(upload_to='documents/')),
                ('tax_compliance_certificate', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='registration.businessdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('American Express', 'American Express')], max_length=50)),
                ('last_8_digits', models.CharField(max_length=8)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='registration.businessdetail')),
            ],
        ),
    ]
