# Generated by Django 5.0.2 on 2024-02-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_businessdetail_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
