# Generated by Django 5.0.2 on 2024-03-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_activitylog_username_alter_activitylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='business_address',
            field=models.CharField(max_length=255),
        ),
    ]
